---
# file: roles/dock/tasks/main.yml

- name: Enable dock autohide
  command: defaults write com.apple.dock autohide -bool false

- name: Remove dock autohide delay
  command: defaults write com.apple.dock autohide-delay -float 0

- name: Quicken animation when showing/hiding dock
  command: defaults write com.apple.dock autohide-time-modifier -float 0

- name: Set dock icon size
  command: defaults write com.apple.dock tilesize -int 40

- name: Change the min/max window effect to scale
  command: defaults write com.apple.dock mineffect -string "scale"

- name: Disable dock magnification
  command: defaults write com.apple.dock magnification -bool true

- name: Bottom align dock position
  command: defaults write com.apple.dock orientation -string bottom

- name: Empty dock of applications
  command: defaults write com.apple.dock persistent-apps -array

- name: Add specific applications to dock
  command: defaults write com.apple.dock persistent-apps -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>{{ item }}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
  with_items:
    - "/Applications/System Preferences.app"
    - "/Applications/Mail.app"
    - "/Applications/Calendar.app"
    - "/Applications/App Store.app"
    - "/Users/{{ user }}/Applications/Spotify.app"
    - "/Users/{{ user }}/Applications/Google Chrome.app"
    - "/Applications/Safari.app"
    - "/Users/{{ user }}/Applications/Firefox.app"
    - "/Applications/iTunes.app"
    - "/Users/{{ user }}/Applications/Steam.app"
    - "/Users/{{ user }}/Applications/Skype.app"
    - "/Applications/Messages.app"
    - "/Users/{{ user }}/Applications/Slack.app"
    - "/Users/{{ user }}/Applications/Hipchat.app"
    - "/Users/{{ user }}/Applications/Sublime Text 2.app"
    - "/Applications/Xcode.app"
    - "/Users/{{ user }}/Applications/Querious.app"
    - "/Users/{{ user }}/Applications/Charles.app"
    - "/Users/{{ user }}/Applications/SourceTree.app"
    - "/Users/{{ user }}/Applications/iTerm.app"

- name: Empty dock of folders
  command: defaults write com.apple.dock persistent-others -array

- name: Add specific folders to dock
  command: defaults write com.apple.dock persistent-others -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>{{ item }}</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
  with_items:
    - "/Users/{{ user }}/Documents"
    - "/Users/{{ user }}/Projects"
    - "/Users/{{ user }}/Applications"

- name: Restart dock
  command: killall Dock
