---
# file: roles/caskroom/tasks/main.yml

- name: Install Cask apps
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - appcleaner
    - caffeine
    - dropbox
    - firefox
    - google-chrome
    - iterm2
    - lastpass
    - paw
    - sequel-pro
    - querious
    - skype
    - spotify
    - vagrant
    - vagrant-manager
    - virtualbox
    - gfxcardstatus
    - sourcetree
    - steam
    - sublime-text
    - slack
    - hipchat
    - charles
    - paintcode
    - adobe-creative-cloud
    - osxfuse

- name: Install NTFS-3G
  homebrew: name={{ item }} state=latest
  with_items:
    - ntfs-3g
